### ISSUE TITLE
Installer fails at Unzipping

### ISSUE THREAD

**Issue by phobos2077** [DrBeef/QuestZDoom#21]
Installer seems not to be working properly. Installed from SideQuest. Oculus v34.
Whatever I'm trying to download it says Downloading, then "Unzipping,,," and that's it, nothing happens. Tried multiple times to download different things, tried re-installing it - nothing. Once it got to the end of download process successfully (back button was unlocked), but once on the main screen - it was still empty as if nothing got downloaded.

Curiously if I look at QuestZDoom folder on device - there are archives downloaded AND unpacked in the tmp folder. Couldn't find any log files or any way to debug the issue on my end.

Tried putting wads manually in the "/QuestZDoom/wads" folder as it says on the website - then clicking "Rescan" many times - nothing happens, all lists on the main UI are empty.

Permission to access files on device was provided in the system pop-up dialog.

**Comment by baggyg** [comment]
Hi, I presume we are talking about the QuestZDoom Launcher. Have a look at the "View Log" button on the right hand side after trying to unzip. 

Considering manually putting wads in also doesn't work I suspect there is a file there it isn't expecting which are causing both processes to crash. I would recommend in the first instance uninstalling the program and manually deleting QuestZDoom. 

Then reinstall and try to download FreeDoom from the Core Games list. Let us know what happens then.

**Comment by phobos2077** [comment]
I tried opening both logs in launcher UI but for me they always reported nothing, like download/unzipping didn't happen at all. Very strange.

I already tried uninstalling, manually deleting QuestZDoom folder (using SideQuest), then re-installing from SideQuest. No go.

Maybe I'll try to record a video or something.

**Comment by baggyg** [comment]
There is no possibility that the Log "would show nothing". It may seem like nothing relevant to you, but it shows how far it is in the process of loading the various things, which I can cross check in the code. 

I will try downloading something as I am on v34 just in case and let you know.

**Comment by baggyg** [comment]
Ok, tried on v34. No problems at all. I need to know what mod it is you are trying to download, as maybe a problem with one which then stops anything else from working. 

Please uninstall, delete the folder, then reinstall and take a video of the completely clean install.

Try FreeDoom mod only and show me what happens.

**Comment by baggyg** [comment]
Oh, also make sure you have enough disk space.

**Comment by phobos2077** [comment]
That's weird. I've just tried re-installing again (and deleting the folder again). That's what happened:

- First run - stuck at "Downloading latest QuestZDoom Version". Waited for 2 minutes then closed the app.
- Second run - shows splash screen for a few seconds (no text), then black screen for few seconds - then app just closed.
- Third run - everything worked as expected, files downloading, show up in the main screen, games run.

Don't know what else to tell you. There were definitely enough space on disk because device was almost empty in both cases. Weird.

Here's a video: https://youtu.be/cJ9wHLdZ6ME

**Comment by phobos2077** [comment]
> There is no possibility that the Log "would show nothing". It may seem like nothing relevant to you, but it shows how far it is in the process of loading the various things, which I can cross check in the code.

There were different cases of download failure:
- Stuck at "Unzipping" - the only two buttons are disabled so you can't do anything except force-close the app. Can't open the logs because of this.
- The same but stuck at different message (don't remember what it was, something like copying files).
- It says download finished, but after returning to the main screen downloaded Freedom wads don't show up. Pressing Rescan does nothing. I opened both logs but saw the same few messages that were shown when I just started the app. Like nothing happened at all.

**Comment by baggyg** [comment]
> First run - stuck at "Downloading latest QuestZDoom Version". Waited for 2 minutes then closed the app.
 
 Sounds like a connectivity issue

> Second run - shows splash screen for a few seconds (no text), then black screen for few seconds - then app just closed.

I expect it had not properly closed from the first time. 

> Third run - everything worked as expected, files downloading, show up in the main screen, games run.

Great, I'll close this issue as there isn't really anything concrete I can test in terms of a bug.

**Comment by phobos2077** [comment]
If I ever see this issue again, I'll make sure to record everything. Maybe download/install process could be made more error proof to show error instead of just hanging forever w/o any indication of what exactly doesn't work? (write access permissions, network issue, etc.)
