### ISSUE TITLE
Siren mod compatibility?

### ISSUE THREAD

**Issue by Wild-Dog** [DrBeef/QuestZDoom#25]
It crashes whenever I run it with DOOM2.Wad

https://www.moddb.com/mods/siren-doom-tc/downloads

**Comment by emawind84** [comment]
Hi, can you specify what version of questzdoom are you using?

**Comment by Wild-Dog** [comment]
1.4.0

**Comment by emawind84** [comment]
It doesn't work on lzdoom, it seems to me a gzdoom only mod, better you contact the author whether is possible to port it to lzdoom as well.

**Comment by Wild-Dog** [comment]
Got it.
