### ISSUE TITLE
MyHouse.Pk3

### ISSUE THREAD

**Issue by Whheat** [DrBeef/QuestZDoom#29]
I’m trying to run MyHouse.pk3 for the first time in vr for immersions sake. But while the .wad works the .pk3 gets an error about mismatching zscripts. Mismatched zscripts and something about expecting one version of gzdoom but requiring another..? I’m new to this so please help.

**Comment by emawind84** [comment]
You need to install the unofficial build of questzsoom
https://github.com/emawind84/QuestZDoom/releases/tag/qzd-r13rc25

**Comment by Whheat** [comment]
Thank you so much! You saved me a major headache.
