### ISSUE TITLE
Better Performance through FFR possible?

### ISSUE THREAD

**Issue by Eispfogel** [DrBeef/QuestZDoom#4]
I don't know if it already is in use - if yes, then i don't see it.
But if possible please implement a FFR solution and let us choose through an option which level we want to use(low, medium, high, high top or dynamic).
Some mods run great, but others need more downsampling, MSAA disabled and even 60Hz. FFR might help in those situations - hopefully!

Thanks again for an awesome Port! You all did great and the launcher is the best thing ever ^^

**Comment by DrBeef** [comment]
I've added a command line parameter, so you can try it out:
```
-ffr <n>
```
where n is one of the values specified in this:

https://developer.oculus.com/documentation/native/android/mobile-ffr/

There's a good chance it makes no difference, but I put it in anyway.

**Comment by Eispfogel** [comment]
Thank you very much! I will check it out - and report!
