### ISSUE TITLE
bug with dual plasma gun

### ISSUE THREAD

**Issue by TranKovak** [DrBeef/QuestZDoom#6]
Hello
first of all thank you for this amazing project, I have more hours in than any other quest game

Actually I play the plutonia experiment with brutal doom, and there is a bug with the plasma gun

I did a little clip (1min) to show you the issue (easy to reproduce). https://youtu.be/wwF8VYY3c7U

I spawn 2 plasma gun and the game auto equip them in one hand and I can't change to another weapon after that even when I run out of ammo.

this is problematic because the game give you the weapon multiple time, I managed to avoid it most of the time, but in level 22 or 23 you are teleported on the weapon directly. I had to use the cheat to get to next level to avoid the weapon :/ 

I hope it's fixable. thank you.

**Comment by emawind84** [comment]
This is an issue with brutal doom, you can try binding weapons key to switch to single weapon. I can also recommend to use my lite version that disable the dual wield and has several optimizations for questzdoom
https://github.com/emawind84/brutal-doom-lite/releases/tag/0.3

I found a thread discussing the problem https://www.moddb.com/mods/brutal-doom/forum/thread/cannot-switch-from-dual-wield-weapons-unless-the-weapon-special-key-is-used
