### ISSUE TITLE
In Heretic when player is on ice with slidey movement disabled, the player moves too slow.

### ISSUE THREAD

**Issue by Matriks404** [DrBeef/QuestZDoom#9]
In **Heretic** (possibly in other WADs/games as well), if player has option "Allow slidey movement (momentum)" in VR options disabled the player barely moves on ice surface, and the player speed/run modifier options don't do much in this situation either.

If slidey movement option is enabled, it works as intended, although it needs to be turned off every time player wants non-slidey movement (if he desires that), which is very annoying.

This happens for example on first half of **E2M4** map called **The Ice Grotto**.

I don't know what reasonable fix would be, maybe add option for slidey movement to be activated only on slippery surfaces, or increase speed somehow?

Proof: [Video link](https://youtu.be/k_pwLfofG6o)

**Comment by emawind84** [comment]
There is absolutely a reasonable fix incoming, working on it.
